name: Release

on:
  - workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/subaction.yaml

  create_release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    # first artifact
    - uses: actions/download-artifact@v3
      with:
        name: somereleasepkg
        path: ./somereleasepkg
    - run: |
      rm -rf somereleasepkg.zip
      zip -r somereleasepkg.zip somereleasepkg
    # upload release
    - uses: ncipollo/release-action@v1
      with:
        commit: 'main'
        tag: '1.0.1'
        allowUpdates: true
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        name: 'Some release'
        removeArtifacts: true
        artifacts: '*.zip'