name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (without v prefix, ex. 1.0.0)'
        default: '1.0.0'
      draft:
        description: 'Should new release be a draft?'
        required: true
        default: true
        options: 
        - true
        - false

jobs:
  build:
    uses: ./.github/workflows/subaction.yaml

  create_release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    # first artifact
    - uses: actions/download-artifact@v3
      with:
        name: somereleasepkg
        path: ./somereleasepkg
    - run: |
        rm -rf somereleasepkg.zip
        zip -r somereleasepkg.zip somereleasepkg
    # upload release
    - uses: ncipollo/release-action@v1
      with:
        commit: 'main'
        tag: 'v${{ inputs.tag }}'
        allowUpdates: true
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        draft: '${{ inputs.draft }}'
        name: 'Some unique name ${{ inputs.tag }}'
        removeArtifacts: true
        artifacts: '*.zip'