name: Release

on:
  - workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/subaction.yaml

  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        commit: "main"
        tag: "1.0.1"
        allowUpdates: true
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        name: "Some release"
        removeArtifacts: true
        artifacts: "somereleasepkg"